brand: ''
application: cabservd
debug: false

tcp:
  bind: ''

api:
  bind: ''

adapter:
  aurservd: 127.0.0.1:5631

postgres:
  dsn: host=localhost user=postgres password= dbname=cabinet port=5432 sslmode=disable TimeZone=Asia/Shanghai
  debug: false

redis:
  address: 127.0.0.1:6379
  logkey: cabservd

loki:
  job: cabservd
  url: http://localhost:3100/loki/api/v1/push