brand: ''

tcp:
  bind: ''

api:
  bind: ''

adapter:
  aurservd: 127.0.0.1:5631

postgres:
  dsn: host=localhost user=postgres password= dbname=cabinet port=5432 sslmode=disable TimeZone=Asia/Shanghai
  debug: false

redis:
  username: ''
  password: ''
  database: 0
  host: 127.0.0.1

loki:
  job: cabservd
  url: http://localhost:3100/loki/api/v1/push