brand: KAIXIN
application: ''
debug: false

maintain:
  token: ''
  ip:
    - 127.0.0.1

tcp:
  bind: 0.0.0.0:16510

api:
  bind: 0.0.0.0:5110

aurservd:
  tcp: 127.0.0.1:5020
  api: http://127.0.0.1:5010

postgres:
  dsn: host=localhost user=postgres password=QGyof&AYf8rSEg*#^zzjiXRN1ykWn*4# dbname=kxservd port=5432 sslmode=disable TimeZone=Asia/Shanghai
  debug: false

redis:
  address: 127.0.0.1:6379
  logkey: kxservd

bmservd:
  XC:
    api: http://127.0.0.1:5210
