// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CabinetBinColumns holds the columns for the "cabinet_bin" table.
	CabinetBinColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "uuid", Type: field.TypeString, Unique: true, Size: 32},
		{Name: "brand", Type: field.TypeString},
		{Name: "sn", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "index", Type: field.TypeInt},
		{Name: "open", Type: field.TypeBool, Default: false},
		{Name: "enable", Type: field.TypeBool, Default: true},
		{Name: "battery_sn", Type: field.TypeString, Default: ""},
		{Name: "voltage", Type: field.TypeFloat64, Default: 0},
		{Name: "current", Type: field.TypeFloat64, Default: 0},
		{Name: "soc", Type: field.TypeFloat64, Default: 0},
		{Name: "soh", Type: field.TypeFloat64, Default: 0},
	}
	// CabinetBinTable holds the schema information for the "cabinet_bin" table.
	CabinetBinTable = &schema.Table{
		Name:       "cabinet_bin",
		Columns:    CabinetBinColumns,
		PrimaryKey: []*schema.Column{CabinetBinColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "cabinetbin_created_at",
				Unique:  false,
				Columns: []*schema.Column{CabinetBinColumns[1]},
			},
			{
				Name:    "cabinetbin_sn_brand",
				Unique:  false,
				Columns: []*schema.Column{CabinetBinColumns[5], CabinetBinColumns[4]},
			},
			{
				Name:    "cabinetbin_index",
				Unique:  false,
				Columns: []*schema.Column{CabinetBinColumns[7]},
			},
			{
				Name:    "cabinetbin_battery_sn",
				Unique:  false,
				Columns: []*schema.Column{CabinetBinColumns[10]},
			},
			{
				Name:    "cabinetbin_soc",
				Unique:  false,
				Columns: []*schema.Column{CabinetBinColumns[13]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CabinetBinTable,
	}
)

func init() {
	CabinetBinTable.Annotation = &entsql.Annotation{
		Table: "cabinet_bin",
	}
}
