// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"github.com/auroraride/cabservd/internal/ent/cabinetbin"
	"github.com/auroraride/cabservd/internal/ent/predicate"

	"entgo.io/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeCabinetBin = "CabinetBin"
)

// CabinetBinMutation represents an operation that mutates the CabinetBin nodes in the graph.
type CabinetBinMutation struct {
	config
	op            Op
	typ           string
	id            *uint64
	created_at    *time.Time
	updated_at    *time.Time
	uuid          *string
	brand         *string
	sn            *string
	name          *string
	index         *int
	addindex      *int
	open          *bool
	enable        *bool
	battery_sn    *string
	voltage       *float64
	addvoltage    *float64
	current       *float64
	addcurrent    *float64
	soc           *float64
	addsoc        *float64
	soh           *float64
	addsoh        *float64
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*CabinetBin, error)
	predicates    []predicate.CabinetBin
}

var _ ent.Mutation = (*CabinetBinMutation)(nil)

// cabinetbinOption allows management of the mutation configuration using functional options.
type cabinetbinOption func(*CabinetBinMutation)

// newCabinetBinMutation creates new mutation for the CabinetBin entity.
func newCabinetBinMutation(c config, op Op, opts ...cabinetbinOption) *CabinetBinMutation {
	m := &CabinetBinMutation{
		config:        c,
		op:            op,
		typ:           TypeCabinetBin,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withCabinetBinID sets the ID field of the mutation.
func withCabinetBinID(id uint64) cabinetbinOption {
	return func(m *CabinetBinMutation) {
		var (
			err   error
			once  sync.Once
			value *CabinetBin
		)
		m.oldValue = func(ctx context.Context) (*CabinetBin, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().CabinetBin.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withCabinetBin sets the old CabinetBin of the mutation.
func withCabinetBin(node *CabinetBin) cabinetbinOption {
	return func(m *CabinetBinMutation) {
		m.oldValue = func(context.Context) (*CabinetBin, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m CabinetBinMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m CabinetBinMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *CabinetBinMutation) ID() (id uint64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *CabinetBinMutation) IDs(ctx context.Context) ([]uint64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uint64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().CabinetBin.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *CabinetBinMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *CabinetBinMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the CabinetBin entity.
// If the CabinetBin object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CabinetBinMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *CabinetBinMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *CabinetBinMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *CabinetBinMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the CabinetBin entity.
// If the CabinetBin object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CabinetBinMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *CabinetBinMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetUUID sets the "uuid" field.
func (m *CabinetBinMutation) SetUUID(s string) {
	m.uuid = &s
}

// UUID returns the value of the "uuid" field in the mutation.
func (m *CabinetBinMutation) UUID() (r string, exists bool) {
	v := m.uuid
	if v == nil {
		return
	}
	return *v, true
}

// OldUUID returns the old "uuid" field's value of the CabinetBin entity.
// If the CabinetBin object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CabinetBinMutation) OldUUID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUUID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUUID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUUID: %w", err)
	}
	return oldValue.UUID, nil
}

// ResetUUID resets all changes to the "uuid" field.
func (m *CabinetBinMutation) ResetUUID() {
	m.uuid = nil
}

// SetBrand sets the "brand" field.
func (m *CabinetBinMutation) SetBrand(s string) {
	m.brand = &s
}

// Brand returns the value of the "brand" field in the mutation.
func (m *CabinetBinMutation) Brand() (r string, exists bool) {
	v := m.brand
	if v == nil {
		return
	}
	return *v, true
}

// OldBrand returns the old "brand" field's value of the CabinetBin entity.
// If the CabinetBin object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CabinetBinMutation) OldBrand(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBrand is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBrand requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBrand: %w", err)
	}
	return oldValue.Brand, nil
}

// ResetBrand resets all changes to the "brand" field.
func (m *CabinetBinMutation) ResetBrand() {
	m.brand = nil
}

// SetSn sets the "sn" field.
func (m *CabinetBinMutation) SetSn(s string) {
	m.sn = &s
}

// Sn returns the value of the "sn" field in the mutation.
func (m *CabinetBinMutation) Sn() (r string, exists bool) {
	v := m.sn
	if v == nil {
		return
	}
	return *v, true
}

// OldSn returns the old "sn" field's value of the CabinetBin entity.
// If the CabinetBin object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CabinetBinMutation) OldSn(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSn is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSn requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSn: %w", err)
	}
	return oldValue.Sn, nil
}

// ResetSn resets all changes to the "sn" field.
func (m *CabinetBinMutation) ResetSn() {
	m.sn = nil
}

// SetName sets the "name" field.
func (m *CabinetBinMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *CabinetBinMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the CabinetBin entity.
// If the CabinetBin object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CabinetBinMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *CabinetBinMutation) ResetName() {
	m.name = nil
}

// SetIndex sets the "index" field.
func (m *CabinetBinMutation) SetIndex(i int) {
	m.index = &i
	m.addindex = nil
}

// Index returns the value of the "index" field in the mutation.
func (m *CabinetBinMutation) Index() (r int, exists bool) {
	v := m.index
	if v == nil {
		return
	}
	return *v, true
}

// OldIndex returns the old "index" field's value of the CabinetBin entity.
// If the CabinetBin object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CabinetBinMutation) OldIndex(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIndex is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIndex requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIndex: %w", err)
	}
	return oldValue.Index, nil
}

// AddIndex adds i to the "index" field.
func (m *CabinetBinMutation) AddIndex(i int) {
	if m.addindex != nil {
		*m.addindex += i
	} else {
		m.addindex = &i
	}
}

// AddedIndex returns the value that was added to the "index" field in this mutation.
func (m *CabinetBinMutation) AddedIndex() (r int, exists bool) {
	v := m.addindex
	if v == nil {
		return
	}
	return *v, true
}

// ResetIndex resets all changes to the "index" field.
func (m *CabinetBinMutation) ResetIndex() {
	m.index = nil
	m.addindex = nil
}

// SetOpen sets the "open" field.
func (m *CabinetBinMutation) SetOpen(b bool) {
	m.open = &b
}

// Open returns the value of the "open" field in the mutation.
func (m *CabinetBinMutation) Open() (r bool, exists bool) {
	v := m.open
	if v == nil {
		return
	}
	return *v, true
}

// OldOpen returns the old "open" field's value of the CabinetBin entity.
// If the CabinetBin object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CabinetBinMutation) OldOpen(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOpen is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOpen requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOpen: %w", err)
	}
	return oldValue.Open, nil
}

// ResetOpen resets all changes to the "open" field.
func (m *CabinetBinMutation) ResetOpen() {
	m.open = nil
}

// SetEnable sets the "enable" field.
func (m *CabinetBinMutation) SetEnable(b bool) {
	m.enable = &b
}

// Enable returns the value of the "enable" field in the mutation.
func (m *CabinetBinMutation) Enable() (r bool, exists bool) {
	v := m.enable
	if v == nil {
		return
	}
	return *v, true
}

// OldEnable returns the old "enable" field's value of the CabinetBin entity.
// If the CabinetBin object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CabinetBinMutation) OldEnable(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEnable is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEnable requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEnable: %w", err)
	}
	return oldValue.Enable, nil
}

// ResetEnable resets all changes to the "enable" field.
func (m *CabinetBinMutation) ResetEnable() {
	m.enable = nil
}

// SetBatterySn sets the "battery_sn" field.
func (m *CabinetBinMutation) SetBatterySn(s string) {
	m.battery_sn = &s
}

// BatterySn returns the value of the "battery_sn" field in the mutation.
func (m *CabinetBinMutation) BatterySn() (r string, exists bool) {
	v := m.battery_sn
	if v == nil {
		return
	}
	return *v, true
}

// OldBatterySn returns the old "battery_sn" field's value of the CabinetBin entity.
// If the CabinetBin object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CabinetBinMutation) OldBatterySn(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBatterySn is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBatterySn requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBatterySn: %w", err)
	}
	return oldValue.BatterySn, nil
}

// ResetBatterySn resets all changes to the "battery_sn" field.
func (m *CabinetBinMutation) ResetBatterySn() {
	m.battery_sn = nil
}

// SetVoltage sets the "voltage" field.
func (m *CabinetBinMutation) SetVoltage(f float64) {
	m.voltage = &f
	m.addvoltage = nil
}

// Voltage returns the value of the "voltage" field in the mutation.
func (m *CabinetBinMutation) Voltage() (r float64, exists bool) {
	v := m.voltage
	if v == nil {
		return
	}
	return *v, true
}

// OldVoltage returns the old "voltage" field's value of the CabinetBin entity.
// If the CabinetBin object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CabinetBinMutation) OldVoltage(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldVoltage is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldVoltage requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldVoltage: %w", err)
	}
	return oldValue.Voltage, nil
}

// AddVoltage adds f to the "voltage" field.
func (m *CabinetBinMutation) AddVoltage(f float64) {
	if m.addvoltage != nil {
		*m.addvoltage += f
	} else {
		m.addvoltage = &f
	}
}

// AddedVoltage returns the value that was added to the "voltage" field in this mutation.
func (m *CabinetBinMutation) AddedVoltage() (r float64, exists bool) {
	v := m.addvoltage
	if v == nil {
		return
	}
	return *v, true
}

// ResetVoltage resets all changes to the "voltage" field.
func (m *CabinetBinMutation) ResetVoltage() {
	m.voltage = nil
	m.addvoltage = nil
}

// SetCurrent sets the "current" field.
func (m *CabinetBinMutation) SetCurrent(f float64) {
	m.current = &f
	m.addcurrent = nil
}

// Current returns the value of the "current" field in the mutation.
func (m *CabinetBinMutation) Current() (r float64, exists bool) {
	v := m.current
	if v == nil {
		return
	}
	return *v, true
}

// OldCurrent returns the old "current" field's value of the CabinetBin entity.
// If the CabinetBin object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CabinetBinMutation) OldCurrent(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCurrent is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCurrent requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCurrent: %w", err)
	}
	return oldValue.Current, nil
}

// AddCurrent adds f to the "current" field.
func (m *CabinetBinMutation) AddCurrent(f float64) {
	if m.addcurrent != nil {
		*m.addcurrent += f
	} else {
		m.addcurrent = &f
	}
}

// AddedCurrent returns the value that was added to the "current" field in this mutation.
func (m *CabinetBinMutation) AddedCurrent() (r float64, exists bool) {
	v := m.addcurrent
	if v == nil {
		return
	}
	return *v, true
}

// ResetCurrent resets all changes to the "current" field.
func (m *CabinetBinMutation) ResetCurrent() {
	m.current = nil
	m.addcurrent = nil
}

// SetSoc sets the "soc" field.
func (m *CabinetBinMutation) SetSoc(f float64) {
	m.soc = &f
	m.addsoc = nil
}

// Soc returns the value of the "soc" field in the mutation.
func (m *CabinetBinMutation) Soc() (r float64, exists bool) {
	v := m.soc
	if v == nil {
		return
	}
	return *v, true
}

// OldSoc returns the old "soc" field's value of the CabinetBin entity.
// If the CabinetBin object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CabinetBinMutation) OldSoc(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSoc is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSoc requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSoc: %w", err)
	}
	return oldValue.Soc, nil
}

// AddSoc adds f to the "soc" field.
func (m *CabinetBinMutation) AddSoc(f float64) {
	if m.addsoc != nil {
		*m.addsoc += f
	} else {
		m.addsoc = &f
	}
}

// AddedSoc returns the value that was added to the "soc" field in this mutation.
func (m *CabinetBinMutation) AddedSoc() (r float64, exists bool) {
	v := m.addsoc
	if v == nil {
		return
	}
	return *v, true
}

// ResetSoc resets all changes to the "soc" field.
func (m *CabinetBinMutation) ResetSoc() {
	m.soc = nil
	m.addsoc = nil
}

// SetSoh sets the "soh" field.
func (m *CabinetBinMutation) SetSoh(f float64) {
	m.soh = &f
	m.addsoh = nil
}

// Soh returns the value of the "soh" field in the mutation.
func (m *CabinetBinMutation) Soh() (r float64, exists bool) {
	v := m.soh
	if v == nil {
		return
	}
	return *v, true
}

// OldSoh returns the old "soh" field's value of the CabinetBin entity.
// If the CabinetBin object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CabinetBinMutation) OldSoh(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSoh is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSoh requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSoh: %w", err)
	}
	return oldValue.Soh, nil
}

// AddSoh adds f to the "soh" field.
func (m *CabinetBinMutation) AddSoh(f float64) {
	if m.addsoh != nil {
		*m.addsoh += f
	} else {
		m.addsoh = &f
	}
}

// AddedSoh returns the value that was added to the "soh" field in this mutation.
func (m *CabinetBinMutation) AddedSoh() (r float64, exists bool) {
	v := m.addsoh
	if v == nil {
		return
	}
	return *v, true
}

// ResetSoh resets all changes to the "soh" field.
func (m *CabinetBinMutation) ResetSoh() {
	m.soh = nil
	m.addsoh = nil
}

// Where appends a list predicates to the CabinetBinMutation builder.
func (m *CabinetBinMutation) Where(ps ...predicate.CabinetBin) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *CabinetBinMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (CabinetBin).
func (m *CabinetBinMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *CabinetBinMutation) Fields() []string {
	fields := make([]string, 0, 14)
	if m.created_at != nil {
		fields = append(fields, cabinetbin.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, cabinetbin.FieldUpdatedAt)
	}
	if m.uuid != nil {
		fields = append(fields, cabinetbin.FieldUUID)
	}
	if m.brand != nil {
		fields = append(fields, cabinetbin.FieldBrand)
	}
	if m.sn != nil {
		fields = append(fields, cabinetbin.FieldSn)
	}
	if m.name != nil {
		fields = append(fields, cabinetbin.FieldName)
	}
	if m.index != nil {
		fields = append(fields, cabinetbin.FieldIndex)
	}
	if m.open != nil {
		fields = append(fields, cabinetbin.FieldOpen)
	}
	if m.enable != nil {
		fields = append(fields, cabinetbin.FieldEnable)
	}
	if m.battery_sn != nil {
		fields = append(fields, cabinetbin.FieldBatterySn)
	}
	if m.voltage != nil {
		fields = append(fields, cabinetbin.FieldVoltage)
	}
	if m.current != nil {
		fields = append(fields, cabinetbin.FieldCurrent)
	}
	if m.soc != nil {
		fields = append(fields, cabinetbin.FieldSoc)
	}
	if m.soh != nil {
		fields = append(fields, cabinetbin.FieldSoh)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *CabinetBinMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case cabinetbin.FieldCreatedAt:
		return m.CreatedAt()
	case cabinetbin.FieldUpdatedAt:
		return m.UpdatedAt()
	case cabinetbin.FieldUUID:
		return m.UUID()
	case cabinetbin.FieldBrand:
		return m.Brand()
	case cabinetbin.FieldSn:
		return m.Sn()
	case cabinetbin.FieldName:
		return m.Name()
	case cabinetbin.FieldIndex:
		return m.Index()
	case cabinetbin.FieldOpen:
		return m.Open()
	case cabinetbin.FieldEnable:
		return m.Enable()
	case cabinetbin.FieldBatterySn:
		return m.BatterySn()
	case cabinetbin.FieldVoltage:
		return m.Voltage()
	case cabinetbin.FieldCurrent:
		return m.Current()
	case cabinetbin.FieldSoc:
		return m.Soc()
	case cabinetbin.FieldSoh:
		return m.Soh()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *CabinetBinMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case cabinetbin.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case cabinetbin.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case cabinetbin.FieldUUID:
		return m.OldUUID(ctx)
	case cabinetbin.FieldBrand:
		return m.OldBrand(ctx)
	case cabinetbin.FieldSn:
		return m.OldSn(ctx)
	case cabinetbin.FieldName:
		return m.OldName(ctx)
	case cabinetbin.FieldIndex:
		return m.OldIndex(ctx)
	case cabinetbin.FieldOpen:
		return m.OldOpen(ctx)
	case cabinetbin.FieldEnable:
		return m.OldEnable(ctx)
	case cabinetbin.FieldBatterySn:
		return m.OldBatterySn(ctx)
	case cabinetbin.FieldVoltage:
		return m.OldVoltage(ctx)
	case cabinetbin.FieldCurrent:
		return m.OldCurrent(ctx)
	case cabinetbin.FieldSoc:
		return m.OldSoc(ctx)
	case cabinetbin.FieldSoh:
		return m.OldSoh(ctx)
	}
	return nil, fmt.Errorf("unknown CabinetBin field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *CabinetBinMutation) SetField(name string, value ent.Value) error {
	switch name {
	case cabinetbin.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case cabinetbin.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case cabinetbin.FieldUUID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUUID(v)
		return nil
	case cabinetbin.FieldBrand:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBrand(v)
		return nil
	case cabinetbin.FieldSn:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSn(v)
		return nil
	case cabinetbin.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case cabinetbin.FieldIndex:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIndex(v)
		return nil
	case cabinetbin.FieldOpen:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOpen(v)
		return nil
	case cabinetbin.FieldEnable:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEnable(v)
		return nil
	case cabinetbin.FieldBatterySn:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBatterySn(v)
		return nil
	case cabinetbin.FieldVoltage:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetVoltage(v)
		return nil
	case cabinetbin.FieldCurrent:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCurrent(v)
		return nil
	case cabinetbin.FieldSoc:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSoc(v)
		return nil
	case cabinetbin.FieldSoh:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSoh(v)
		return nil
	}
	return fmt.Errorf("unknown CabinetBin field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *CabinetBinMutation) AddedFields() []string {
	var fields []string
	if m.addindex != nil {
		fields = append(fields, cabinetbin.FieldIndex)
	}
	if m.addvoltage != nil {
		fields = append(fields, cabinetbin.FieldVoltage)
	}
	if m.addcurrent != nil {
		fields = append(fields, cabinetbin.FieldCurrent)
	}
	if m.addsoc != nil {
		fields = append(fields, cabinetbin.FieldSoc)
	}
	if m.addsoh != nil {
		fields = append(fields, cabinetbin.FieldSoh)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *CabinetBinMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case cabinetbin.FieldIndex:
		return m.AddedIndex()
	case cabinetbin.FieldVoltage:
		return m.AddedVoltage()
	case cabinetbin.FieldCurrent:
		return m.AddedCurrent()
	case cabinetbin.FieldSoc:
		return m.AddedSoc()
	case cabinetbin.FieldSoh:
		return m.AddedSoh()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *CabinetBinMutation) AddField(name string, value ent.Value) error {
	switch name {
	case cabinetbin.FieldIndex:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddIndex(v)
		return nil
	case cabinetbin.FieldVoltage:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddVoltage(v)
		return nil
	case cabinetbin.FieldCurrent:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCurrent(v)
		return nil
	case cabinetbin.FieldSoc:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddSoc(v)
		return nil
	case cabinetbin.FieldSoh:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddSoh(v)
		return nil
	}
	return fmt.Errorf("unknown CabinetBin numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *CabinetBinMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *CabinetBinMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *CabinetBinMutation) ClearField(name string) error {
	return fmt.Errorf("unknown CabinetBin nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *CabinetBinMutation) ResetField(name string) error {
	switch name {
	case cabinetbin.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case cabinetbin.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case cabinetbin.FieldUUID:
		m.ResetUUID()
		return nil
	case cabinetbin.FieldBrand:
		m.ResetBrand()
		return nil
	case cabinetbin.FieldSn:
		m.ResetSn()
		return nil
	case cabinetbin.FieldName:
		m.ResetName()
		return nil
	case cabinetbin.FieldIndex:
		m.ResetIndex()
		return nil
	case cabinetbin.FieldOpen:
		m.ResetOpen()
		return nil
	case cabinetbin.FieldEnable:
		m.ResetEnable()
		return nil
	case cabinetbin.FieldBatterySn:
		m.ResetBatterySn()
		return nil
	case cabinetbin.FieldVoltage:
		m.ResetVoltage()
		return nil
	case cabinetbin.FieldCurrent:
		m.ResetCurrent()
		return nil
	case cabinetbin.FieldSoc:
		m.ResetSoc()
		return nil
	case cabinetbin.FieldSoh:
		m.ResetSoh()
		return nil
	}
	return fmt.Errorf("unknown CabinetBin field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *CabinetBinMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *CabinetBinMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *CabinetBinMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *CabinetBinMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *CabinetBinMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *CabinetBinMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *CabinetBinMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown CabinetBin unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *CabinetBinMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown CabinetBin edge %s", name)
}
