// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/auroraride/cabservd/internal/ent/cabinetbin"
	"github.com/auroraride/cabservd/internal/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	cabinetbinMixin := schema.CabinetBin{}.Mixin()
	cabinetbinMixinFields0 := cabinetbinMixin[0].Fields()
	_ = cabinetbinMixinFields0
	cabinetbinFields := schema.CabinetBin{}.Fields()
	_ = cabinetbinFields
	// cabinetbinDescCreatedAt is the schema descriptor for created_at field.
	cabinetbinDescCreatedAt := cabinetbinMixinFields0[0].Descriptor()
	// cabinetbin.DefaultCreatedAt holds the default value on creation for the created_at field.
	cabinetbin.DefaultCreatedAt = cabinetbinDescCreatedAt.Default.(func() time.Time)
	// cabinetbinDescUpdatedAt is the schema descriptor for updated_at field.
	cabinetbinDescUpdatedAt := cabinetbinMixinFields0[1].Descriptor()
	// cabinetbin.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	cabinetbin.DefaultUpdatedAt = cabinetbinDescUpdatedAt.Default.(func() time.Time)
	// cabinetbin.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	cabinetbin.UpdateDefaultUpdatedAt = cabinetbinDescUpdatedAt.UpdateDefault.(func() time.Time)
	// cabinetbinDescUUID is the schema descriptor for uuid field.
	cabinetbinDescUUID := cabinetbinFields[0].Descriptor()
	// cabinetbin.UUIDValidator is a validator for the "uuid" field. It is called by the builders before save.
	cabinetbin.UUIDValidator = cabinetbinDescUUID.Validators[0].(func(string) error)
	// cabinetbinDescOpen is the schema descriptor for open field.
	cabinetbinDescOpen := cabinetbinFields[5].Descriptor()
	// cabinetbin.DefaultOpen holds the default value on creation for the open field.
	cabinetbin.DefaultOpen = cabinetbinDescOpen.Default.(bool)
	// cabinetbinDescEnable is the schema descriptor for enable field.
	cabinetbinDescEnable := cabinetbinFields[6].Descriptor()
	// cabinetbin.DefaultEnable holds the default value on creation for the enable field.
	cabinetbin.DefaultEnable = cabinetbinDescEnable.Default.(bool)
	// cabinetbinDescVoltage is the schema descriptor for voltage field.
	cabinetbinDescVoltage := cabinetbinFields[8].Descriptor()
	// cabinetbin.DefaultVoltage holds the default value on creation for the voltage field.
	cabinetbin.DefaultVoltage = cabinetbinDescVoltage.Default.(float64)
	// cabinetbinDescCurrent is the schema descriptor for current field.
	cabinetbinDescCurrent := cabinetbinFields[9].Descriptor()
	// cabinetbin.DefaultCurrent holds the default value on creation for the current field.
	cabinetbin.DefaultCurrent = cabinetbinDescCurrent.Default.(float64)
}
