// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/auroraride/cabservd/internal/ent/cabinetbin"
	"github.com/auroraride/cabservd/internal/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	cabinetbinMixin := schema.CabinetBin{}.Mixin()
	cabinetbinMixinFields0 := cabinetbinMixin[0].Fields()
	_ = cabinetbinMixinFields0
	cabinetbinFields := schema.CabinetBin{}.Fields()
	_ = cabinetbinFields
	// cabinetbinDescCreatedAt is the schema descriptor for created_at field.
	cabinetbinDescCreatedAt := cabinetbinMixinFields0[0].Descriptor()
	// cabinetbin.DefaultCreatedAt holds the default value on creation for the created_at field.
	cabinetbin.DefaultCreatedAt = cabinetbinDescCreatedAt.Default.(func() time.Time)
	// cabinetbinDescUpdatedAt is the schema descriptor for updated_at field.
	cabinetbinDescUpdatedAt := cabinetbinMixinFields0[1].Descriptor()
	// cabinetbin.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	cabinetbin.DefaultUpdatedAt = cabinetbinDescUpdatedAt.Default.(func() time.Time)
	// cabinetbin.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	cabinetbin.UpdateDefaultUpdatedAt = cabinetbinDescUpdatedAt.UpdateDefault.(func() time.Time)
}
