// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/auroraride/cabservd/internal/ent/bin"
	"github.com/auroraride/cabservd/internal/ent/cabinet"
	"github.com/auroraride/cabservd/internal/ent/console"
	"github.com/auroraride/cabservd/internal/ent/scan"
	"github.com/auroraride/cabservd/internal/ent/schema"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	binMixin := schema.Bin{}.Mixin()
	binMixinFields0 := binMixin[0].Fields()
	_ = binMixinFields0
	binFields := schema.Bin{}.Fields()
	_ = binFields
	// binDescCreatedAt is the schema descriptor for created_at field.
	binDescCreatedAt := binMixinFields0[0].Descriptor()
	// bin.DefaultCreatedAt holds the default value on creation for the created_at field.
	bin.DefaultCreatedAt = binDescCreatedAt.Default.(func() time.Time)
	// binDescUpdatedAt is the schema descriptor for updated_at field.
	binDescUpdatedAt := binMixinFields0[1].Descriptor()
	// bin.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	bin.DefaultUpdatedAt = binDescUpdatedAt.Default.(func() time.Time)
	// bin.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	bin.UpdateDefaultUpdatedAt = binDescUpdatedAt.UpdateDefault.(func() time.Time)
	// binDescUUID is the schema descriptor for uuid field.
	binDescUUID := binFields[0].Descriptor()
	// bin.UUIDValidator is a validator for the "uuid" field. It is called by the builders before save.
	bin.UUIDValidator = binDescUUID.Validators[0].(func(string) error)
	// binDescOpen is the schema descriptor for open field.
	binDescOpen := binFields[6].Descriptor()
	// bin.DefaultOpen holds the default value on creation for the open field.
	bin.DefaultOpen = binDescOpen.Default.(bool)
	// binDescEnable is the schema descriptor for enable field.
	binDescEnable := binFields[7].Descriptor()
	// bin.DefaultEnable holds the default value on creation for the enable field.
	bin.DefaultEnable = binDescEnable.Default.(bool)
	// binDescHealth is the schema descriptor for health field.
	binDescHealth := binFields[8].Descriptor()
	// bin.DefaultHealth holds the default value on creation for the health field.
	bin.DefaultHealth = binDescHealth.Default.(bool)
	// binDescBatteryExists is the schema descriptor for battery_exists field.
	binDescBatteryExists := binFields[9].Descriptor()
	// bin.DefaultBatteryExists holds the default value on creation for the battery_exists field.
	bin.DefaultBatteryExists = binDescBatteryExists.Default.(bool)
	// binDescBatterySn is the schema descriptor for battery_sn field.
	binDescBatterySn := binFields[10].Descriptor()
	// bin.DefaultBatterySn holds the default value on creation for the battery_sn field.
	bin.DefaultBatterySn = binDescBatterySn.Default.(string)
	// binDescVoltage is the schema descriptor for voltage field.
	binDescVoltage := binFields[11].Descriptor()
	// bin.DefaultVoltage holds the default value on creation for the voltage field.
	bin.DefaultVoltage = binDescVoltage.Default.(float64)
	// binDescCurrent is the schema descriptor for current field.
	binDescCurrent := binFields[12].Descriptor()
	// bin.DefaultCurrent holds the default value on creation for the current field.
	bin.DefaultCurrent = binDescCurrent.Default.(float64)
	// binDescSoc is the schema descriptor for soc field.
	binDescSoc := binFields[13].Descriptor()
	// bin.DefaultSoc holds the default value on creation for the soc field.
	bin.DefaultSoc = binDescSoc.Default.(float64)
	// binDescSoh is the schema descriptor for soh field.
	binDescSoh := binFields[14].Descriptor()
	// bin.DefaultSoh holds the default value on creation for the soh field.
	bin.DefaultSoh = binDescSoh.Default.(float64)
	cabinetMixin := schema.Cabinet{}.Mixin()
	cabinetMixinFields0 := cabinetMixin[0].Fields()
	_ = cabinetMixinFields0
	cabinetFields := schema.Cabinet{}.Fields()
	_ = cabinetFields
	// cabinetDescCreatedAt is the schema descriptor for created_at field.
	cabinetDescCreatedAt := cabinetMixinFields0[0].Descriptor()
	// cabinet.DefaultCreatedAt holds the default value on creation for the created_at field.
	cabinet.DefaultCreatedAt = cabinetDescCreatedAt.Default.(func() time.Time)
	// cabinetDescUpdatedAt is the schema descriptor for updated_at field.
	cabinetDescUpdatedAt := cabinetMixinFields0[1].Descriptor()
	// cabinet.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	cabinet.DefaultUpdatedAt = cabinetDescUpdatedAt.Default.(func() time.Time)
	// cabinet.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	cabinet.UpdateDefaultUpdatedAt = cabinetDescUpdatedAt.UpdateDefault.(func() time.Time)
	// cabinetDescOnline is the schema descriptor for online field.
	cabinetDescOnline := cabinetFields[0].Descriptor()
	// cabinet.DefaultOnline holds the default value on creation for the online field.
	cabinet.DefaultOnline = cabinetDescOnline.Default.(bool)
	// cabinetDescPower is the schema descriptor for power field.
	cabinetDescPower := cabinetFields[1].Descriptor()
	// cabinet.DefaultPower holds the default value on creation for the power field.
	cabinet.DefaultPower = cabinetDescPower.Default.(bool)
	// cabinetDescEnable is the schema descriptor for enable field.
	cabinetDescEnable := cabinetFields[5].Descriptor()
	// cabinet.DefaultEnable holds the default value on creation for the enable field.
	cabinet.DefaultEnable = cabinetDescEnable.Default.(bool)
	consoleFields := schema.Console{}.Fields()
	_ = consoleFields
	// consoleDescStep is the schema descriptor for step field.
	consoleDescStep := consoleFields[6].Descriptor()
	// console.DefaultStep holds the default value on creation for the step field.
	console.DefaultStep = consoleDescStep.Default.(int)
	scanMixin := schema.Scan{}.Mixin()
	scanMixinFields0 := scanMixin[0].Fields()
	_ = scanMixinFields0
	scanFields := schema.Scan{}.Fields()
	_ = scanFields
	// scanDescCreatedAt is the schema descriptor for created_at field.
	scanDescCreatedAt := scanMixinFields0[0].Descriptor()
	// scan.DefaultCreatedAt holds the default value on creation for the created_at field.
	scan.DefaultCreatedAt = scanDescCreatedAt.Default.(func() time.Time)
	// scanDescUpdatedAt is the schema descriptor for updated_at field.
	scanDescUpdatedAt := scanMixinFields0[1].Descriptor()
	// scan.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	scan.DefaultUpdatedAt = scanDescUpdatedAt.Default.(func() time.Time)
	// scan.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	scan.UpdateDefaultUpdatedAt = scanDescUpdatedAt.UpdateDefault.(func() time.Time)
	// scanDescUUID is the schema descriptor for uuid field.
	scanDescUUID := scanFields[0].Descriptor()
	// scan.DefaultUUID holds the default value on creation for the uuid field.
	scan.DefaultUUID = scanDescUUID.Default.(func() uuid.UUID)
	// scanDescEfficient is the schema descriptor for efficient field.
	scanDescEfficient := scanFields[2].Descriptor()
	// scan.DefaultEfficient holds the default value on creation for the efficient field.
	scan.DefaultEfficient = scanDescEfficient.Default.(bool)
}
