// Code generated by ent, DO NOT EDIT.

package ent

// GetTableName returns table name for Bin.
func (b *Bin) GetTableName() string {
	return "bin"
}

// GetTableName returns table name for Cabinet.
func (c *Cabinet) GetTableName() string {
	return "cabinet"
}

// GetTableName returns table name for Console.
func (c *Console) GetTableName() string {
	return "console"
}

// GetTableName returns table name for Scan.
func (s *Scan) GetTableName() string {
	return "scan"
}
