// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CabinetBin is the predicate function for cabinetbin builders.
type CabinetBin func(*sql.Selector)
